### ISSUE TITLE
About difference between SMPL from SMPLify-x and NeuralAnnot

### ISSUE THREAD

**Issue by amituofo1996** [mks0601/NeuralAnnot_RELEASE#4]
Hi，you do such great work!
I find two links released of you.
[SMPL from SMPLify-x](https://drive.google.com/drive/folders/12fCumEgs9PXT-dAaOGq0EDpl9dGKKorF)
[NeuralAnnot](https://drive.google.com/drive/folders/1ySxiuTCSdUEqbgTcx7bx02uMglPOkKjc)
I find this two links question about data size.
just like Human36M_subject1_SMPL_NeuralAnnot.json(114.9) vs Human36M_subject1_smpl_param.json(34.8MB)
Is there something diferent? I want to get some detail difference about these two file. Thanks!

**Comment by mks0601** [comment]
You can check that fits from SMPLify-X have only a SMPL param for every 5 samples (5 fps).
On the other hand, ours has a SMPL param for every sample (1 fps).
The reason for this is that SMPLify-X is too slow to get SMPL params for all frames. Ours is much faster so that I could get SMPL params for all frames.

**Comment by amituofo1996** [comment]
Thanks for you quick reply
